name: PHP Build

on:
  push:
    branches: [ main , dev]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: 1234567890@Eu
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"
    strategy: 
      fail-fast: true
      
    steps:
    
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@2.30.0
      with:
        php-version: 8.3
        extensions: mbstring, sqlsrv, iconv
        tools: phpunit:9.6.19, composer:2.7.3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Setup MSSQL for Master Data
      run: sqlcmd -S localhost -U SA -P 1234567890@Eu -Q 'create database testing'
      
    - name: Execute Tests
      run: phpunit --configuration tests/phpunit.xml
